### PR TITLE
add sass styling, background image, format textbox

### PR DESCRIPTION
**Pull request by biglovisa**
- add sass 
- add styling to the problems page
- small formatting of the problem box

### CODE REVIEW

**Comment by mikedao** [comment]
@applegrain Whoa, whoa, whoa, you took out the fact that Jeff Wan Likes pumpkins?

**Comment by biglovisa** [comment]
@mikedao Oh thanks for reminding me! I removed it, but was going to add it somewhere else (and clearly forgot). I was thinking of adding a picture of a pumpkin, and when you click it the pumpkin picture appears. Maybe we can randomize a new picture of Jwan everyday?

**Comment by mikedao** [comment]
I don’t have that many good pictures of Jwan. I also think we can do better picture of taylor swift.

Let me find one.

On September 14, 2015 at 10:35:14 AM, Lovisa Svallingson (notifications@github.com) wrote:

Oh thanks for reminding me! I removed, but was going to add it somewhere else. I was thinking of adding a picture of a pumpkin, and when you click it the pumpkin picture appears. Maybe we can randomize a new picture of Jwan everyday?

**Comment by biglovisa** [comment]
Yeah, I just picked the first high res one I found haha.

**Comment by mikedao** [comment]
I would love something like this:

http://www.billboard.com/files/styles/promo_650/public/media/taylor-swift-shake-it-off-video-2-2014-billboard-650.jpg

On September 14, 2015 at 10:52:09 AM, Lovisa Svallingson (notifications@github.com) wrote:

Yeah, I just picked the first high res one I found haha.

**Comment by biglovisa** [comment]
Background changed @mikedao :+1:

**Pull request merged**
